openapi: 3.0.1
info:
  title: Constancy API
  version: 0.1.0
  description: API Service endpoints
  contact:
    email: jonathan.lee.devel@gmail.com
    name: Jonathan Lee
servers:
  - url: "/"
tags:
  - name: Jenkins
    description: Jenkins (Proxy) APIs
paths:
  /jenkins/start-builds:
    post:
      tags:
        - Jenkins
      summary: Start a collection of Jenkins builds
      operationId: jenkins-start-builds
      requestBody:
        description: New user signing up
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DraftBookSchema"
      responses:
        "200":
          description: Book was added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookSchema"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestSchema"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorSchema"
components:
  schemas:
    BadRequestSchema:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: 'PATH: [author] ;; MESSAGE: "author" is required'
      required:
        - error
    ServerErrorSchema:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Internal server error
      required:
        - error
    NotFoundErrorSchema:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Item not found
      required:
        - error
    DraftBookSchema:
      type: object
      properties:
        name:
          type: string
          description: Name of the book
          example: The Hitchhiker's Guide to the Galaxy
        author:
          type: string
          description: Name of the author
          example: Douglas Adams
      required:
        - name
        - author
    BookSchema:
      allOf:
        - $ref: "#/components/schemas/DraftBookSchema"
      type: object
      properties:
        _id:
          type: string
          description: MongoDB id of the document
          example: 5d7224d3b40b1a1a046697dd
        createdAt:
          type: number
          description: Created at timestamp in miliseconds
          example: 1616158942428
        updatedAt:
          type: number
          description: Updated at timestamp in miliseconds
          example: 1616158942428
      required:
        - _id
        - createdAt
        - updatedAt
